apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      containers:
        - name: my-container
          image: httpd:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "15m"
              memory: "100Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      containers:
        - name: my-container
          image: httpd:latest
          ports:
            - containerPort: 80